# Generated by Django 5.1 on 2024-08-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('twf-cleaning-1', 'twf-cleaning-1'), ('twf-cleaning-3', 'twf-cleaning-3'), ('twf-cleaning-2', 'twf-cleaning-2')], max_length=14),
        ),
    ]
